Docs for Laravel style relations
wintercms/docs pull request #176
Opened 2024-02-27 08:15 UTC by bennothommo

Refs: https://github.com/wintercms/storm/pull/167

2024-02-27 11:48 UTC, mjauvin commented on database/relations.md
> +Alternatively, you may also use the `Relation` attribute on the method to define it is as a relation method:
```suggestion
Alternatively, you may also use the `Relation` attribute on the method to define it as a relation method:
```

2024-03-01 08:02 UTC, LukeTowers commented on database/relations.md
> +}
Does this example actually work given that chaining the query methods will cause a builder to be returned instead of a relation instance?

2024-03-01 08:20 UTC, bennothommo commented on database/relations.md
> +}
Good spot - no it probably wouldn't with the return type being `HasMany`, but it would if it were using the Relation attribute.

2024-03-01 08:25 UTC, bennothommo commented on database/relations.md
> +}
Fixed that example.

2024-07-29 21:31 UTC, LukeTowers commented on database/relations.md
> -> **NOTE:** If you are selecting specific columns in your query and want to load relationships as well, you need to make sure that the columns that contain the keying data (i.e. `id`, `foreign_key`,
Is this no longer true?

2024-07-29 21:42 UTC, LukeTowers requested changes

2024-07-29 21:42 UTC, LukeTowers commented on database/relations.md
> +        'profile' => 'Acme\Blog\Models\Profile',
```suggestion
        'profile' => \Acme\Blog\Models\Profile::class,
```

2024-07-29 21:42 UTC, LukeTowers commented on database/relations.md
> +        'posts' => 'Acme\Blog\Models\Post',
```suggestion
        'posts' => \Acme\Blog\Models\Post::class,
```

2024-07-29 21:42 UTC, LukeTowers commented on database/relations.md
> +> **Note:** Method style relation definition is available from Winter v1.2.5.
```suggestion
> **NOTE:** Method style relation definition is available from Winter v1.2.5.
```
Specific version to be updated once we merge the PR

2024-07-29 21:42 UTC, LukeTowers commented on database/relations.md
> +- Relation methods defined in the model class, synonymous with Laravel, available since Winter CMS v1.2.5 (Method style)
```suggestion
- Property-based array configuration in the model class (Property style)
- Relation methods defined in the model class, [synonymous with Laravel](https://laravel.com/docs/9.x/eloquent-relationships#defining-relationships) (Method style)
```

2024-07-29 21:42 UTC, LukeTowers commented on database/relations.md
> +`->notPushable()` | Sets this relation to not be saved when `push()` is run on the primary model.
Thoughts / precedent for `x() / notX()` vs `x() / x(false)`?

2024-07-29 21:42 UTC, LukeTowers commented on database/relations.md
> +> **Note:** If your relation is constrained in this fashion, the object returned will be a query builder, not the original relation class. You will need to use the `Relation` attribute to mark method
```suggestion
> **NOTE:** If your relation is constrained in this fashion, the object returned will be a query builder, not the original relation class. You will need to use the `Relation` attribute to mark methods that return query builders as a relation method.
```

2024-07-29 21:42 UTC, LukeTowers commented on database/relations.md
> +    }
What happens when someone double declares the relationship like this? Do we throw an exception warning them of this when parsing the property style config?

2024-07-29 21:42 UTC, LukeTowers commented on database/relations.md
> +The `belongsTo`, `hasOne`, `hasOneThrough` and `morphOne` relationships allow you to define a default model that will be returned if the given relationship is `null`. This pattern is often referred t
```suggestion
The `belongsTo`, `hasOne`, `hasOneThrough`, and `morphOne` relationships allow you to define a default model that will be returned if the given relationship is `null`. This pattern is often referred to as the [Null Object pattern](https://en.wikipedia.org/wiki/Null_Object_pattern) and can help remove conditional checks in your code. In the following example, the `user` relation will return an empty `Acme\Blog\Models\User` model if no `user` is attached to the post:
```

2024-07-30 05:09 UTC, bennothommo commented on database/relations.md
> -> **NOTE:** If you are selecting specific columns in your query and want to load relationships as well, you need to make sure that the columns that contain the keying data (i.e. `id`, `foreign_key`,
Nope, fairly certain that Laravel connects the required foreign keys regardless of any `select()` calls limiting the columns. Probably worth a unit test for this though :)

2024-07-30 05:11 UTC, bennothommo commented on database/relations.md
> +        'posts' => 'Acme\Blog\Models\Post',
I'd like to keep one example of a string like this, to show it's accepted, even if it's not our "preferred" way.

2024-07-30 05:15 UTC, bennothommo commented on database/relations.md
> +`->notPushable()` | Sets this relation to not be saved when `push()` is run on the primary model.
I find with chained methods that set flags like this, it's more readable to use just method names. This is my own view though, I don't have any specific precedent to cite for it. I added the `not...` methods purely to allow for people to reverse a flag in any sort of extension.

2024-07-30 05:17 UTC, bennothommo commented on database/relations.md
> +    }
The method function will supersede the property style config. Note that a lot of the functionality we have for property style relations is literally to emulate a relation method being available, so if the method exists, it will be used instead.

2024-07-30 15:40 UTC, LukeTowers commented on database/relations.md
> -> **NOTE:** If you are selecting specific columns in your query and want to load relationships as well, you need to make sure that the columns that contain the keying data (i.e. `id`, `foreign_key`,
@bennothommo this is the original issue that prompted that note to be included, if you could do up a unit test that would be fantastic ❤️: https://github.com/octobercms/october/issues/2944

2024-07-30 15:43 UTC, LukeTowers commented on database/relations.md
> +        'posts' => 'Acme\Blog\Models\Post',
Meh, I'd prefer not to. If someone wants to do it that way and it works for them, good for them. The documentation should be showing people how we expect things to be done; and a string literal working as a class reference is a language feature, so I think it's unnecessary that we provide an example of it in our docs just for completeness sake. Technically `array('item1', 'item2')` is also a supported way of doing things, but there's no way I want to be encouraging that behaviour.

The ::class constant is extremely helpful, both in making it obvious when you have a typo and making code navigation in editors / IDEs much easier / faster.

2024-07-30 15:45 UTC, LukeTowers commented on database/relations.md
> +`->notPushable()` | Sets this relation to not be saved when `push()` is run on the primary model.
I think the pattern of having the toggle be in the parameters is fairly well established cross-language at this point, so I think my preference would be to not have the `notX()` methods present or documented. 

`->pushable(false)` vs `->notPushable()` seems to be about the same amount of readable to me. @mjauvin @jaxwilko any thoughts?

2024-07-30 15:47 UTC, LukeTowers commented on database/relations.md
> +    }
Can we make the property stuff throw an exception if it encounters this if it doesn't already? I wouldn't want someone to define a config in a property that isn't actually looked at because they have a method present.

2024-07-30 15:50 UTC, mjauvin commented on database/relations.md
> +`->notPushable()` | Sets this relation to not be saved when `push()` is run on the primary model.
I'm good with `->pushable(true/false)`

2024-09-27 18:23 UTC, LukeTowers commented
@bennothommo do you have any thoughts on the pending comments here?

2024-09-28 04:02 UTC, bennothommo commented on database/relations.md
> +`->notPushable()` | Sets this relation to not be saved when `push()` is run on the primary model.
Can we have both? I do like how declarative method naming reads over having to use parameters and relying on the IDE to tell me what they mean - even if it's something as simple as an enable toggle.

2024-10-03 07:03 UTC, LukeTowers commented
@bennothommo ping

2024-10-03 13:25 UTC, bennothommo commented
@LukeTowers I left a comment here for one of your threads: https://github.com/wintercms/docs/pull/176#discussion_r1779358319

2024-10-03 13:27 UTC, bennothommo commented on database/relations.md
> +    }
We wouldn't be able to catch all cases of this. If, say, there's a `phone` definition in the relation properties, and a `phone` method in the same model, and you were to call `$model->phone()`, the method is going to be called without issue. It would only be in cases where you were to call `$model->phone` that we could possibly pick it up, but as you can see, the other way of calling the relation is naturally going to go to the method over the property.

2024-10-03 16:13 UTC, mjauvin commented on database/relations.md
> +    }
@bennothommo what about calling it in twig without "()" ? Does it default to the method or the property ?

2024-10-03 17:42 UTC, LukeTowers commented on database/relations.md
> +`->notPushable()` | Sets this relation to not be saved when `push()` is run on the primary model.
@bennothommo sure, I'm fine with both

2024-10-03 17:44 UTC, LukeTowers commented on database/relations.md
> +    }
Let's add the logic to detect it anyways, better to have some protection in place than none

2024-10-03 22:16 UTC, bennothommo commented on database/relations.md
> +    }
@mjauvin it would default to the property first in Twig based on its access logic rules.

2024-10-05 08:19 UTC, LukeTowers commented
TODO before PRs can be merged:

- [ ] https://github.com/wintercms/docs/pull/176#discussion_r1697186528
- [ ] https://github.com/wintercms/docs/pull/176#discussion_r1786630512
- [ ] https://github.com/wintercms/docs/pull/176#discussion_r1779358319

2024-10-08 01:27 UTC, bennothommo commented on database/relations.md
> -> **NOTE:** If you are selecting specific columns in your query and want to load relationships as well, you need to make sure that the columns that contain the keying data (i.e. `id`, `foreign_key`,
@LukeTowers my mistake - Laravel doesn't do this:

![image](https://github.com/user-attachments/assets/dbb7513f-ba5c-4797-9fa1-85bf3f7e8c4c)

It does when retrieving the relations directly, but if you're creating a query and you don't include the necessary ID fields, it will prevent the relations from being linked. I will restore the note.

2024-10-08 02:01 UTC, bennothommo commented on database/relations.md
> +    }
Done as of https://github.com/wintercms/storm/pull/167/commits/55603fc00f5780bd7805e42bce4a209305ef9c02

2024-10-08 02:01 UTC, bennothommo commented
@LukeTowers all comments should be resolved now.

2024-10-08 03:28 UTC, LukeTowers commented on database/relations.md
> +}
Last thing required, need to document the methods I added a couple years ago to make adding new relationships easier: https://github.com/wintercms/storm/commit/b977610d361cc25f24b05062e40a83a6d53680a8

2024-10-09 06:25 UTC, LukeTowers approved these changes

2024-10-09 06:26 UTC, merged