Improving usability
wintercms/docs pull request #41
Opened 2021-12-27 16:29 UTC by WebVPF

Improving usability - backend section

2021-12-28 02:14 UTC, bennothommo commented on ajax-javascript-api.md
> +<div class="attributes-table-precessor"></div>
@WebVPF what is the purpose of this inline styling?

2021-12-28 02:15 UTC, bennothommo commented on ajax-update-partials.md
> +```none
@WebVPF for codeblocks with `none`, could you just remove the `none` so they are interpreted as raw text?

2021-12-28 02:18 UTC, bennothommo commented on backend-reorder.md
> +	buttons: reorder_toolbar
@WebVPF spaces only for whitespace, please :)

```suggestion
    # Partial for toolbar buttons
    buttons: reorder_toolbar
```

2021-12-28 02:20 UTC, bennothommo commented
@WebVPF great work with this. I've just left a couple of fixes for you to do.

2021-12-28 06:43 UTC, WebVPF commented on ajax-javascript-api.md
> +<div class="attributes-table-precessor"></div>
no styles:

![2021-12-28_083121](https://user-images.githubusercontent.com/61043464/147536120-4bd4f030-158b-4b65-b92c-2561f39ead14.jpg)

with styles:

![2021-12-28_083447](https://user-images.githubusercontent.com/61043464/147536243-a3b091cf-f540-439b-87b0-09de8e4700a7.jpg)

the solution is taken here (before table): https://github.com/wintercms/docs/blob/main/ajax-attributes-api.md

2021-12-28 07:08 UTC, WebVPF commented on ajax-update-partials.md
> +```none
@bennothommo If you use modern libraries to highlight the code, the `none` indicator will style the code block but will not highlight the syntax of the code.
Perhaps in the future you will want to use the PrismJS (https://prismjs.com) library on the documentation site.
Without the indicator, the code block will not be styled at all.

Maybe it's better to leave `none`?

2021-12-28 07:16 UTC, WebVPF commented
I will continue working when this pull request is accepted.

2021-12-28 15:54 UTC, LukeTowers commented on ajax-update-partials.md
> +```none
would this not just be `json`?

2021-12-28 16:05 UTC, LukeTowers commented on ajax-update-partials.md
> +```none
@WebVPF if you would be willing to just change these examples to be in the form of:

```js
$.request('onExample', { update: {
    mypartial: '#myDiv'
}});
```
instead so we can use JS highlighting that would be great

2021-12-28 16:06 UTC, LukeTowers commented on backend-controllers-ajax.md
> +```php
```suggestion
```html
```

2021-12-28 16:07 UTC, LukeTowers commented on backend-reorder.md
> +}
inner indentation needs to be fixed here

2021-12-28 16:08 UTC, LukeTowers commented on backend-reorder.md
> +	$query->withTrashed();
```suggestion
    $query->withTrashed();
```

2021-12-28 16:10 UTC, LukeTowers commented on backend-users.md
> +```html
```suggestion
```php
```

2021-12-28 16:11 UTC, WebVPF commented on ajax-update-partials.md
> +```none
@LukeTowers No. Will compile without language indicator.

without `none`:

```html
<pre>
    <code></code>
</pre>
```

with `none`:

```html
<pre class="language-none">
    <code></code>
</pre>
```

This is used to style a block of code. This is how they define it in CSS:

```css
pre[class*="language-"] {
    background: #f5f2f0;
}
```

if necessary I can delete all `none`

2021-12-28 16:13 UTC, LukeTowers commented on ajax-update-partials.md
> +```none
@bennothommo I think I'm fine with the none indicator then, any further thoughts?

2021-12-28 16:18 UTC, bennothommo commented on ajax-update-partials.md
> +```none
I'd rather not include it. We're styling non-defined code blocks the same as defined code blocks in the docs, so it doesn't matter.

2021-12-28 16:37 UTC, WebVPF commented on backend-reorder.md
> +}
@LukeTowers How to fix it?

2021-12-28 16:46 UTC, WebVPF commented on backend-reorder.md
> +}
Like this?

```
// [...]
}
```

2021-12-29 11:00 UTC, WebVPF commented
Remove `none`?
What to use where there is no language indicator? Indentation or three apostrophes?

2021-12-29 11:57 UTC, bennothommo commented
@WebVPF let's use three apostrophes as the standard from now on. In the case of `none`, simply change it so it's no language at all.

2021-12-29 13:34 UTC, WebVPF commented
It is bad without `none` because it is not clear where the beginning of the code is.

2022-01-02 14:58 UTC, LukeTowers requested changes

2022-01-02 14:58 UTC, LukeTowers commented on backend-lists.md
> +```html
```suggestion
```php
```

2022-01-02 14:58 UTC, LukeTowers commented on database-query.md
> +            ->get();
```suggestion
    ->crossJoin('colors')
    ->get();
```

2022-01-02 14:58 UTC, LukeTowers commented on database-query.md
> +                    ->groupBy('user_id');
```suggestion
    ->select('user_id', Db::raw('MAX(created_at) as last_post_created_at'))
    ->where('is_published', true)
    ->groupBy('user_id');
```

2022-01-02 14:58 UTC, LukeTowers commented on database-query.md
> +            })->get();
```suggestion
    ->joinSub($latestPosts, 'latest_posts', function ($join) {
        $join->on('users.id', '=', 'latest_posts.user_id');
    })->get();
```

2022-01-02 14:58 UTC, LukeTowers commented on database-query.md
> +                ->get();
```suggestion
    ->where('options->language', 'en')
    ->get();
```

2022-01-02 14:58 UTC, LukeTowers commented on database-query.md
> +                ->get();
```suggestion
    ->where('preferences->dining->meal', 'salad')
    ->get();
```

2022-01-02 14:58 UTC, LukeTowers commented on database-query.md
> +                ->get();
```suggestion
    ->whereJsonContains('options->languages', 'en')
    ->get();
```

2022-01-02 14:58 UTC, LukeTowers commented on database-query.md
> +                ->get();
```suggestion
    ->whereJsonContains('options->languages', ['en', 'de'])
    ->get();
```

2022-01-02 14:58 UTC, LukeTowers commented on database-query.md
> +                ->get();
```suggestion
    ->whereJsonLength('options->languages', 0)
    ->get();
```

2022-01-02 14:58 UTC, LukeTowers commented on database-query.md
> +                ->get();
```suggestion
    ->whereJsonLength('options->languages', '>', 1)
    ->get();
```

2022-01-02 14:58 UTC, LukeTowers commented on database-query.md
> +                ->get();
```suggestion
    ->when($role, function ($query, $role) {
        return $query->where('role_id', $role);
    })
    ->get();
```

2022-01-02 14:58 UTC, LukeTowers commented on database-query.md
> +                ->get();
```suggestion
    ->when($sortBy, function ($query, $sortBy) {
        return $query->orderBy($sortBy);
    }, function ($query) {
        return $query->orderBy('name');
    })
    ->get();
```

2022-01-02 14:58 UTC, LukeTowers commented on database-relations.md
> +```
```suggestion
```sql
```

2022-01-02 14:58 UTC, LukeTowers commented on database-structure.md
> +        ->onDelete('cascade');
```suggestion
    ->references('id')
    ->on('users')
    ->onDelete('cascade');
```

2022-01-02 15:04 UTC, LukeTowers approved these changes

2022-01-02 15:06 UTC, merged

2022-01-02 21:35 UTC, LukeTowers commented
Thanks for all your work on this @WebVPF!